name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      # Falla porque no tenemos la API levantada??
      # - name: Run tests con WebdriverIO
      #   run: |
      #     npm start &
      #     npx wait-on http://localhost:4200
      #     npm run wdio

      # - name: Inject API URL environment variable
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     sed -i "s|__CAMPAIGNS_3000_API_URL__|${{ secrets.CAMPAIGNS_3000_API_URL }}|g" src/environments/environment.prod.ts
      #     cat src/environments/environment.prod.ts

      - name: Build project
        run: npm run build

      # - name: Deploy to Render
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: JorgeLNJunior/render-deploy@v1.4.7
      #   with:
      #     service_id: ${{ secrets.RENDER_SERVICE_ID }}
      #     api_key: ${{ secrets.RENDER_API_KEY }}
      #     clear_cache: true # Útil para Angular para evitar problemas de versiones viejas
      #     wait_deploy: false # El workflow esperará a que Render diga "Live"
      #     github_deployment: true
      #     deployment_environment: 'production'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Render
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deploy # Le ponemos un ID para poder referenciarlo
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}