name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      # 1. Checkout del frontend
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          path: frontend

      # 2. Checkout de la API
      - name: Checkout API
        uses: actions/checkout@v4
        with:
          repository: avillalbapronoide/campaigns-3000-api
          path: api

      # 3. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 4. Instalar dependencias de la API
      - name: Install API dependencies
        working-directory: api
        run: npm install

      # 5. Resetear base de datos
      - name: Reset database
        working-directory: api
        run: |
          # rm -f newsletter.db
          sqlite3 newsletter.db < reset_db.sql

      # 6. Levantar la API en background
      - name: Start API
        working-directory: api
        run: |
          npm start &
          npx wait-on http://localhost:3009 || npx wait-on http://localhost:3009 --timeout 30000

      # 7. Instalar dependencias del frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 8. Levantar el frontend y ejecutar tests
      - name: Run E2E tests with WebdriverIO
        working-directory: frontend
        run: |
          npm start &
          npx wait-on http://localhost:4200
          npm run wdio

      # 9. Build del proyecto
      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Deploy to Render
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deploy # Le ponemos un ID para poder referenciarlo
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}